name: Continuous Integration

on:
  push:
    branches: '**'
    pull_request:
      - master
    tags-ignore: '**'

jobs:
  format:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        go: [ '1.22' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - run: gofmt -l $(find . -type f -name '*.go') 2>&1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  test:
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]
        go: [ '1.22' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - run: go test ./...
        env:
          CGO_ENABLED: 1

  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: 'macos-latest'
            goos: 'darwin'
            goarch: 'amd64'
          - os: 'macos-latest'
            goos: 'darwin'
            goarch: 'arm64'
          - os: 'ubuntu-latest'
            goos: 'linux'
            goarch: 'amd64'
          - os: 'windows-latest'
            goos: 'windows'
            goarch: 'amd64'
        go: [ '1.22' ]

    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - if: matrix.target.goos == 'darwin' && matrix.target.goarch == 'arm64'
        run: |
          echo SDKROOT=$(xcrun --sdk macosx --show-sdk-path) >> $GITHUB_ENV

      - run: |
          go build -v .
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}
          CGO_ENABLED: 1

      - uses: actions/upload-artifact@v4
        with:
          name: alpaca-${{ matrix.target.goos }}-${{ matrix.target.goarch }}
          path: alpaca
